server:
  port: 8081

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1

  application:
    name: mushroom-schedule

  datasource:
    url: jdbc:mysql://localhost:3306/mushroom
    username: root
    password: testroot1234!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        type: trace
        dialect: org.hibernate.dialect.MySQLDialect